# Clustering 

In [17]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
from numpy import random, float

df=pd.read_csv("/Users/kaoichen/Downloads/movie_metadata.csv")
df = df.dropna(how = 'any')
df.shape

(3756, 28)

In [18]:
#things to take into account: budget, gross, imdb_score

col=['budget','gross','imdb_score']
df=df[df['title_year']>=2012]
df=df[col]
df['budget']=df['budget'].apply(lambda x: float(x/10000000))
df['gross']=df['gross'].apply(lambda x: float(x/10000000))

df.head()

budget      gross  imdb_score
2    24.50  20.007417         6.8
3    25.00  44.813064         8.5
5    26.37   7.305868         6.6
8    25.00  45.899160         7.5
10   25.00  33.024906         6.9

In [21]:
model = KMeans(n_clusters=4)
model = model.fit(df) 

print model.cluster_centers_

[[  9.22052632   9.8794319    6.51513158]
 [  2.28414245   2.69166157   6.34302326]
 [ 16.43061224  21.86742364   7.14693878]
 [ 15.90818182  41.03829333   7.54545455]]
